# Generated by Django 2.2.4 on 2019-10-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20, null=True)),
                ('movie_name', models.CharField(default='', max_length=20)),
                ('store_id', models.CharField(default='', max_length=20)),
                ('alie_customer_id', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
