# Generated by Django 2.2.4 on 2019-10-16 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0, null=True)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('timestamp', models.DateField(default=datetime.datetime.now, null=True)),
                ('user_email', models.EmailField(default='', max_length=254, null=True)),
                ('user_name', models.CharField(default='', max_length=20)),
                ('no_of_views', models.IntegerField(default=0, null=True)),
                ('alie_customer_id', models.IntegerField(default=0, null=True)),
                ('store_id', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
