# Generated by Django 2.2.4 on 2019-10-16 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
