# Generated by Django 2.2.4 on 2019-10-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191016_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='alie_customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='store_id',
            field=models.IntegerField(default=0),
        ),
    ]
